import csv, argparse, time, datetime
from hashmaker import *

dupe_path = 0
dupe_count = 1
dupe_filesize = 2
dupe_hash = 3

dupes = {}
hashmake = hashMaker()


def dupefullsize(dupecountfile, dupefullfile):
    with open(dupecountfile, "r") as dupefile:
        dupecountreader = csv.reader(dupefile)

        with open(dupefullfile, "w") as fullfile:
            fullwriter = csv.writer(fullfile)
        
            for dupe in dupecountreader:
                print (dupe)
                control = hashmake.makeOneHash(dupe[dupe_path], 1)
                fullhash = hashmake.makeOneHash(dupe[dupe_path], 99999999999999999999)
                
                if control == dupe[dupe_hash]:
                    control = "YES"
                else:
                    control = "NO"

                if fullhash == dupe[dupe_hash]:
                    match = "YES"
                else:
                    match = "NO"

                fullwriter.writerow([dupe[dupe_path], control, match, fullhash, dupe[dupe_hash]])





if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="Dupe Full Size",
                                     description="Given a CSV of dupes generated by Dupe Counter, will go back and scan the full file and see if it's still a duplicate.")
    parser.add_argument('dupecountfile', help="Input CSV file containing dupecount")
    parser.add_argument(
        'dupefullfile', help="Output CSV containing whether or not each dupe is still a dupe")
    args = parser.parse_args()

    dupefullsize(args.dupecountfile, args.dupefullfile)